import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.sass';
import SearchBar from './SearchBar';

type Props = {
  children: JSX.Element;
};

const Layout = ({ children }: Props) => {
  return (
    <div className={styles.layout}>
      <Head>
        <title>FoodieZone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="web development, typescript, react" />
      </Head>
      <Link href="/">
        <a>
          <div className={styles.title}>FoodieZone</div>
        </a>
      </Link>
      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default Layout;
